# https://docs.travis-ci.com/user/languages/objective-c/
os: osx
osx_image: xcode10.1	
language: swift # Save compiled cocoapods

xcode_workspace: Buddies.xcworkspace # path to the workspace to build
xcode_scheme: Buddies
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone XR

before_install: 
  - openssl aes-256-cbc -K $encryption_key -iv $encryption_iv -in Buddies/Keys.plist.enc -out Buddies/Keys.plist -d

install:
  - echo Hello

# Build pushes to master:
branches:
  only: 
    - master

# Uploads test coverage to codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - tail -n +1 `find /Users/travis/Library/Developer/Xcode/DerivedData -name "StandardOutputAndStandardError.txt"`

